"""empty message

Revision ID: 56247965e41b
Revises: 5c3583515b68
Create Date: 2022-09-05 14:13:33.148654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56247965e41b'
down_revision = '5c3583515b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_registration', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_registration')

    # ### end Alembic commands ###
